#'原名' = [ '译名', 出现次数 ]

"浩巳" = ["浩巳", 4549]
"祐一郎" = ["祐一郎", 3299]
"歌穂" = ["歌穗", 2150]
"炎之華" = ["炎之华", 1534]
"麻美" = ["麻美", 1518]
"理奈" = ["理奈", 1384]
"水魂都" = ["水魂都", 809]
"奈緒" = ["奈绪", 612]
"軍平" = ["军平", 322]
"二宮" = ["二宫", 228]
"薬師寺" = ["药师寺", 223]
"菅原" = ["菅原", 217]
"鈴木" = ["铃木", 172]
"森久保" = ["森久保", 126]
"鏡香" = ["镜香", 121]
"虹乃" = ["虹乃", 114]
"田村" = ["田村", 95]
"学生たち" = ["学生们", 82]
"部員たち" = ["部员们", 73]
"部員Ａ" = ["部员A", 67]
"部員Ｂ" = ["部员B", 65]
"立花" = ["立花", 60]
"大田" = ["大田", 57]
"学生１" = ["学生1", 56]
"学生" = ["学生", 52]
"竹内" = ["竹内", 51]
"チンピラたち" = ["小混混们", 50]
"部員Ｃ" = ["部员C", 50]
"学生２" = ["学生2", 45]
"木下" = ["木下", 39]
"学生３" = ["学生3", 36]
"小僧たち" = ["少年们", 35]
"学生４" = ["学生4", 30]
"３人" = ["三人", 27]
"男１" = ["男1", 27]
"炎之華の声" = ["炎之华的声音", 26]
"義理の父" = ["义父", 25]
"ホームレスＡ" = ["流浪汉A", 24]
"男３" = ["男3", 24]
"男２" = ["男2", 22]
"部員Ｄ" = ["部员D", 19]
"仲間１" = ["同伴1", 19]
"看護婦" = ["护士", 19]
"赤尾" = ["赤尾", 19]
"ホームレスたち" = ["流浪汉们", 16]
"学生７" = ["学生7", 16]
"部長" = ["部长", 16]
"男４" = ["男4", 16]
"篤" = ["笃", 16]
"用務員１" = ["校工1", 15]
"男の声" = ["男人的声音", 15]
"母親" = ["母亲", 15]
"女の子" = ["女孩子", 14]
"小僧４" = ["少年4", 14]
"西村" = ["西村", 14]
"仲間２" = ["同伴2", 12]
"小僧５" = ["少年5", 12]
"学生５" = ["学生5", 12]
"男６" = ["男6", 12]
"男８" = ["男8", 12]
"用務員２" = ["校工2", 11]
"用務員３" = ["校工3", 11]
"仲間３" = ["同伴3", 11]
"小僧６" = ["少年6", 10]
"女の声" = ["女人的声音", 10]
"黒岩" = ["黑岩", 10]
"ホームレスＢ" = ["流浪汉B", 9]
"女性の声" = ["女性的声音", 9]
"放送" = ["广播", 9]
"水泳部員２" = ["游泳部员2", 8]
"水泳部員１" = ["游泳部员1", 8]
"理奈の声" = ["理奈的声音", 8]
"運動部員" = ["运动部员", 8]
"学生６" = ["学生6", 8]
"部員Ｈ" = ["部员H", 8]
"部員Ｆ" = ["部员F", 8]
"水泳部員３" = ["游泳部员3", 7]
"用務員たち" = ["校工们", 7]
"小僧２" = ["少年2", 7]
"女教師" = ["女教师", 7]
"小僧３" = ["少年3", 7]
"教頭" = ["副校长", 7]
"男７" = ["男7", 7]
"ホームレスＣ" = ["流浪汉C", 6]
"新入生１" = ["新生1", 6]
"麻美の声" = ["麻美的声音", 6]
"？？？" = ["？？？", 6]
"小僧１" = ["少年1", 6]
"男１０" = ["男10", 6]
"部員Ｅ" = ["部员E", 6]
"男５" = ["男5", 6]
"男９" = ["男9", 6]
"大崎" = ["大崎", 6]
"水泳部員たち" = ["游泳部员们", 5]
"ホームレスＤ" = ["流浪汉D", 5]
"チンピラ１" = ["小混混1", 5]
"教師" = ["教师", 5]
"チンピラ２" = ["小混混2", 4]
"学生の声２" = ["学生的声音2", 4]
"水魂都の声" = ["水魂都的声音", 4]
"大田・竹内" = ["大田和竹内", 4]
"女の子１" = ["女孩子1", 4]
"仲間４" = ["同伴4", 4]
"部員Ｇ" = ["部员G", 4]
"ひろみ" = ["浩巳", 4]
"島崎" = ["岛崎", 4]
"男" = ["男", 4]
"声" = ["声音", 4]
"暗い目の学生" = ["眼神阴暗的学生", 3]
"竹内・大田" = ["竹内和大田", 3]
"看護婦の声" = ["护士的声音", 3]
"女の子３" = ["女孩子3", 3]
"女の子２" = ["女孩子2", 3]
"女の子４" = ["女孩子4", 3]
"ＯＢたち" = ["校友们", 3]
"男１１" = ["男11", 3]
"学生Ｃ" = ["学生C", 3]
"学生８" = ["学生8", 3]
"学生９" = ["学生9", 3]
"教諭" = ["教师", 3]
"鏡華" = ["镜华", 3]
"級長" = ["班长", 3]
"女" = ["女人", 3]
"学生の声１" = ["学生的声音1", 2]
"新入生たち" = ["新生们", 2]
"学生の声３" = ["学生的声音3", 2]
"学生１・２" = ["学生1和2", 2]
"学生１０" = ["学生10", 2]
"同級生２" = ["同班同学2", 2]
"新入生２" = ["新生2", 2]
"水泳部員" = ["游泳部员", 2]
"同級生１" = ["同班同学1", 2]
"学年主任" = ["年级主任", 2]
"宅配便" = ["快递", 2]
"学生Ｂ" = ["学生B", 2]
"学生Ａ" = ["学生A", 2]
"１２３４５６７８９０１" = ["12345678901", 1]
"車内アナウンス" = ["车内广播", 1]
"理奈・炎之華" = ["理奈和炎之华", 1]
"大田、竹内" = ["大田和竹内", 1]
"小僧２・３" = ["少年2和3", 1]
"薬師寺の声" = ["药师寺的声音", 1]
"写真部部員" = ["摄影部成员", 1]
"学生６・７" = ["学生6和7", 1]
"部員Ａ・Ｃ" = ["部员A和C", 1]
"新入生３" = ["新生3", 1]
"新入生５" = ["新生5", 1]
"新入生４" = ["新生4", 1]
"チンピラ" = ["小混混", 1]
"仲間５" = ["同伴5", 1]
"男たち" = ["男人们", 1]
"みこと" = ["水魂都", 1]
"電話" = ["电话", 1]
"男性" = ["男性", 1]
"日直" = ["值日生", 1]
"河野" = ["河野", 1]

