# searchStr 可缩写为 org, replaceStr 可缩写为 rep (译前和译后字典同样适用)
gptDict = [
    # 语义标注

    { org = "[title]", rep = "[title]", note = "场景标题标记，请保留，标记的该行文本是整个场景（后续对话）的标题，非角色对话或旁白" },
    { org = "[select]", rep = "[select]", note = "选项文本标记，请保留，标记的该行是玩家可选择的选项条目，非角色对话或旁白，通常出现在分支节点处" },

    # ----------------------------------
    # 主要角色
    {org = "祐一郎", rep = "祐一郎", note = "人名，男性，全名“伊达祐一郎”（伊達 祐一郎，だて ゆういちろう），学生，后毕业且当上了校工，冷静、狡猾、善于操纵、报复心强、性欲旺盛，军平的徒弟"},
    {org = "伊達祐一郎", rep = "伊达祐一郎", note = "人名全名，男性，即“祐一郎”"},
    {org = "伊達", rep = "伊达", note = "人名姓氏，祐一郎的姓氏"},
    {org = "伊達君", rep = "伊达君", note = "人名，男性，祐一郎的称呼"},
    {org = "伊達さん", rep = "伊达君", note = "人名，男性，祐一郎的称呼"},
    
    {org = "浩巳", rep = "浩巳", note = "人名，男性，全名“水树浩巳”（水樹 浩巳，みずき ひろみ），学生，经常被同学欺负，家庭贫困，父母失踪，在亲戚间辗转，被麻美诱惑，称麻美为“妈妈”，内向、胆小、容易哭、心地善良，患有某种导致身体和性发育迟缓的疾病"},
    {org = "水樹浩巳", rep = "水树浩巳", note = "人名全名，男性，即“浩巳”"},
    {org = "水樹", rep = "水树", note = "人名姓氏，浩巳的姓氏"},
    {org = "水樹君", rep = "水树君", note = "人名，男性，浩巳的称呼"},
    {org = "浩巳君", rep = "浩巳君", note = "人名，男性，浩巳的称呼"},
    {org = "浩巳さん", rep = "浩巳君", note = "人名，男性，浩巳的称呼"},
    {org = "ひろみ", rep = "浩巳", note = "人名，男性，浩巳的称呼"},
    {org = "ひろみくん", rep = "浩巳君", note = "人名，男性，浩巳的称呼"},
    
    
    {org = "理奈", rep = "理奈", note = "人名，女性，全名“朝仓理奈”（朝倉 理奈，あさくら りな），青年，校医，性格沉稳温和、关心学生"},
    {org = "朝倉理奈", rep = "朝仓理奈", note = "人名全名，女性，即“理奈”"},
    {org = "朝倉", rep = "朝仓", note = "人名姓氏，理奈的姓氏"},
    {org = "理奈先生", rep = "理奈老师", note = "人名，女性，理奈的称呼"},
    {org = "朝倉先生", rep = "朝仓老师", note = "人名，女性，理奈的称呼"},
    
    {org = "麻美", rep = "麻美", note = "人名，女性，全名“长泽麻美”（長沢 麻美，ながさわ あさみ），成年女性（30岁左右），数学教师，游泳部顾问，表面严厉、口不择言、看不起学生，实则欲求不满、内心孤独、脆弱，因丈夫出轨、孩子去世而精神不稳定"},
    {org = "長沢麻美", rep = "长泽麻美", note = "人名全名，女性，即“麻美”"},
    {org = "長沢", rep = "长泽", note = "人名姓氏，麻美的姓氏"},
    {org = "長沢先生", rep = "长泽老师", note = "人名，女性，麻美的称呼"},
    {org = "麻美先生", rep = "麻美老师", note = "人名，女性，麻美的称呼"},
    
    
    {org = "奈緒", rep = "奈绪", note = "人名，女性，全名“筱原奈绪”（篠原 奈緒，しのはら なお），青年，说话温和，善良，但有点脆弱，社会研究的兼职讲师，曾是祐一郎的家庭教师，后被祐一郎胁迫成为其奴仆"},
    {org = "篠原奈緒", rep = "筱原奈绪", note = "人名全名，女性，即“奈绪”"},
    {org = "篠原", rep = "筱原", note = "人名姓氏，奈绪的姓氏"},
    {org = "篠原先生", rep = "筱原老师", note = "人名，女性，奈绪的称呼"},
    {org = "奈緒先生", rep = "奈绪老师", note = "人名，女性，奈绪的称呼"},
    
    {org = "炎之華", rep = "炎之华", note = "人名，女性，全名“藤堂炎之华”（藤堂 炎之華，とうどう ほのか），青年，化学教师，外表冷酷、沉默寡言、难以接近，但内心坚强、执着，对妹妹水魂都极富爱心和牺牲精神，水魂都的姐姐"},
    {org = "藤堂炎之華", rep = "藤堂炎之华", note = "人名全名，女性，即“炎之华”"},
    {org = "藤堂先生", rep = "藤堂老师", note = "人名，女性，炎之华的称呼"},
    {org = "炎之華先生", rep = "炎之华老师", note = "人名，女性，炎之华的称呼"},

    {org = "水魂都", rep = "水魂都", note = "人名，女性，全名“藤堂水魂都”（藤堂 水魂都，とうどう みこと），学生，天真，炎之华的妹妹（无血缘关系），患有一种由心理创伤引起的、导致身体停止发育的罕见疾病"},
    {org = "藤堂水魂都", rep = "藤堂水魂都", note = "人名全名，女性，即“水魂都”"},
    {org = "水魂都ちゃん", rep = "小水魂都", note = "人名，女性，水魂都的称呼"},
    {org = "みこと", rep = "水魂都", note = "人名，女性，水魂都的称呼"},

    {org = "藤堂", rep = "藤堂", note = "人名姓氏，炎之华和水魂都的姓氏"},
    
    {org = "歌穂", rep = "歌穗", note = "人名，女性，全名“结城歌穗”（結城 歌穂，ゆうき かほ），青年，校长朱雀院镜香的女儿，英语老师，善良，友好"},
    {org = "結城歌穂", rep = "结城歌穗", note = "人名全名，女性，即“歌穗”"},
    {org = "結城", rep = "结城", note = "人名姓氏，歌穗的姓氏"},
    {org = "結城先生", rep = "结城老师", note = "人名，女性，歌穗的称呼"},
    {org = "歌穂先生", rep = "歌穗老师", note = "人名，女性，歌穗的称呼"},
    
    {org = "軍平", rep = "军平", note = "人名，男性，姓氏为“岩村”，老年，表面是校工，实则前任校长，祐一郎的师傅，深藏不露、老谋深算、精通“肉欲之道”"},
    {org = "軍平さん", rep = "军平先生", note = "人名，男性，军平的称呼"},
    {org = "岩村", rep = "岩村", note = "人名姓氏，军平的姓氏"},
    {org = "岩村さん", rep = "岩村先生", note = "人名，男性，军平的称呼"},
    

    {org = "虹乃", rep = "虹乃", note = "人名，女性，全名“杉崎虹乃”（杉崎 虹乃，すぎさき にじの），成年女性，副校长"},
    {org = "杉崎虹乃", rep = "杉崎虹乃", note = "人名全名，女性，即“虹乃”"},
    {org = "杉崎", rep = "杉崎", note = "人名姓氏，虹乃的姓氏"},
    
    {org = "鏡香", rep = "镜香", note = "人名，女性，全名“朱雀院镜香”（朱雀院 鏡香，すざくいん きょうか），成年女性，学园校长，歌穗的妈妈"},
    {org = "朱雀院鏡香", rep = "朱雀院镜香", note = "人名全名，女性，即“镜香”"},
    {org = "朱雀院", rep = "朱雀院", note = "人名姓氏，镜香的姓氏"},
    
    {org = "薬師寺", rep = "药师寺", note = "人名，男性，学生，粗暴、霸凌者头目，经常欺凌浩巳"},

    # ----------------------------------
    # 其他角色/术语
    {org = "乱れ胡蝶", rep = "乱蝶", note = "一种双头震动棒（双头性玩具）"},
    {org = "バーリトゥード", rep = "无限制格斗", note = "一种几乎没有规则限制的徒手格斗形式"},

    {org = "二宮", rep = "二宫", note = "人名，男性，学生，与祐一郎、大田、竹内同班"},
    {org = "大田", rep = "大田", note = "人名，男性，学生，与祐一郎、二宫、竹内同班"},
    {org = "竹内", rep = "竹内", note = "人名，男性，学生，与祐一郎、二宫、大田同班"},
    {org = "立花", rep = "立花", note = "人名，男性，学生"},
    {org = "鈴木", rep = "铃木", note = "人名，男性，学生"},
    {org = "田村", rep = "田村", note = "人名，男性，学生"},
    {org = "木下", rep = "木下", note = "人名，男性，学生"},
    
    {org = "篤", rep = "笃", note = "人名，男性"},

    {org = "菅原", rep = "菅原", note = "人名，男性，生物教师，性格怪癖，有收集癖（女教师的爱液、阴毛），是写真部顾问"},
    {org = "菅原先生", rep = "菅原老师", note = "人名，男性，菅原的称呼"},
    
    {org = "森久保", rep = "森久保", note = "人名，男性，教师，祐一郎等人的班主任，对歌穗有好感，性格软弱"},
    {org = "森久保先生", rep = "森久保老师", note = "人名，男性，森久保的称呼"},
]
